### ISSUE TITLE
Empty Slides error

### ISSUE THREAD

**Issue by fabianmoronzirfas** [frntl/frontal#97]
Empty slides create an error

**Comment by fabianmoronzirfas** [comment]
```
Uncaught Exception:
TypeError: Cannot read property 'replace' of undefined
Please report this to https://github.com/chjj/marked.
    at Lexer.lex (/Applications/frontal.0.8.8b.app/Contents/Resources/app/node_modules/marked/lib/marked.js:138:5)
    at Function.Lexer.lex (/Applications/frontal.0.8.8b.app/Contents/Resources/app/node_modules/marked/lib/marked.js:129:16)
    at marked (/Applications/frontal.0.8.8b.app/Contents/Resources/app/node_modules/marked/lib/marked.js:1218:31)
    at /Applications/frontal.0.8.8b.app/Contents/Resources/app/lib/parser.js:127:16
    at Array.forEach (native)
    at Object.md2htmlMarked (/Applications/frontal.0.8.8b.app/Contents/Resources/app/lib/parser.js:107:13)
    at slides (/Applications/frontal.0.8.8b.app/Contents/Resources/app/lib/slides.js:28:23)
    at processing (/Applications/frontal.0.8.8b.app/Contents/Resources/app/lib/processor.js:31:41)
    at reload (/Applications/frontal.0.8.8b.app/Contents/Resources/app/lib/reload-presentation.js:20:48)
    at FSWatcher.<anonymous> (/Applications/frontal.0.8.8b.app/Contents/Resources/app/lib/watcher.js:19:36)
```
